DROP USER KAFKALAB IDENTIFIED BY KAFKALAB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

CREATE USER KAFKALAB IDENTIFIED BY KAFKALAB DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
alter profile DEFAULT limit PASSWORD_REUSE_TIME unlimited;
alter profile DEFAULT limit PASSWORD_LIFE_TIME  unlimited;
grant connect, resource,create synonym,create view to KAFKALAB;

-- List Users
SELECT USERNAME FROM ALL_USERS WHERE USERNAME='KAFKALAB';
