/*
Por cada tabla a crear:

	1. Delete table por si esta creada
	2. Create table
Create or replace synonim

*/

-- TAbla topic TEST 1
DROP TABLE KAFKALAB.TOPIC_TEST_1 PURGE;

CREATE TABLE KAFKALAB.TOPIC_TEST_1 (CADENA VARCHAR2(4000));

-- Taula TOPIC TEST 2
DROP TABLE KAFKALAB.TOPIC_TEST_2 PURGE;

CREATE TABLE KAFKALAB.TOPIC_TEST_2 (CADENA VARCHAR2(4000));

-- Taula Procedure

DROP TABLE KAFKA_PRECREADA_SPROC PURGE;

CREATE TABLE KAFKA_PRECREADA_SPROC ("ROWNUMID" NUMBER not null,"CHGTMST" timestamp not null,"NUMPERSO" NUMBER not null,"LOCALIDA" VARCHAR2(1000) not null,"DIRECCIO" varchar2(1000) not null,"FECULTIM" DATE NOT NULL ENABLE,"HORULTIM" DATE NOT NULL ENABLE,"FECALTA" DATE NOT NULL ENABLE);



CREATE OR REPLACE SYNONYM KAFKALAB.SV_SYNKW_TOPIC_TEST FOR KAFKALAB.TOPIC_TEST_1;

CREATE OR REPLACE SYNONYM KAFKALAB.SV_SYNKR_TOPIC_TEST FOR KAFKALAB.TOPIC_TEST_2;
